"""add_is_internal_to_financial_models

Revision ID: ed090fa4ea04
Revises: 368403e438ec
Create Date: 2026-04-23 12:06:01.794015+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed090fa4ea04'
down_revision: Union[str, None] = '368403e438ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hutang_usaha', sa.Column('is_internal', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_kasbon_karyawan_unit'), 'kasbon_karyawan', ['unit'], unique=False)
    op.add_column('piutang_usaha', sa.Column('is_internal', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piutang_usaha', 'is_internal')
    op.drop_index(op.f('ix_kasbon_karyawan_unit'), table_name='kasbon_karyawan')
    op.drop_column('hutang_usaha', 'is_internal')
    # ### end Alembic commands ###
