"""Add JasaServis table

Revision ID: 853ac368726a
Revises: 07a4e2c50169
Create Date: 2026-02-03 17:40:14.066609+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '853ac368726a'
down_revision: Union[str, None] = '07a4e2c50169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jasa_servis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('harga', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jasa_servis_nama'), 'jasa_servis', ['nama'], unique=False)
    op.alter_column('pengeluaran_bengkel', 'kategori',
               existing_type=mysql.ENUM('biaya_operasional', 'biaya_lainnya', 'prive', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'biaya_operasional'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pengeluaran_bengkel', 'kategori',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('biaya_operasional', 'biaya_lainnya', 'prive', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'biaya_operasional'"))
    op.drop_index(op.f('ix_jasa_servis_nama'), table_name='jasa_servis')
    op.drop_table('jasa_servis')
    # ### end Alembic commands ###
