"""make additional costs tied to armada

Revision ID: 7aa25f4a7e70
Revises: df64ee66aab1
Create Date: 2026-02-20 22:14:56.349745+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7aa25f4a7e70'
down_revision: Union[str, None] = 'df64ee66aab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jasa_angkut_biaya_lainnya', sa.Column('armada_id', sa.Integer(), nullable=True))
    op.alter_column('jasa_angkut_biaya_lainnya', 'muatan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'jasa_angkut_biaya_lainnya', 'armada_jasa_angkut', ['armada_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jasa_angkut_biaya_lainnya', type_='foreignkey')
    op.alter_column('jasa_angkut_biaya_lainnya', 'muatan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('jasa_angkut_biaya_lainnya', 'armada_id')
    # ### end Alembic commands ###
