"""Add customer_vehicles table

Revision ID: 749fe60716a7
Revises: 853ac368726a
Create Date: 2026-02-03 18:18:47.605551+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749fe60716a7'
down_revision: Union[str, None] = '853ac368726a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('plat_nomor', sa.String(length=15), nullable=False),
    sa.Column('jenis_unit', sa.String(length=50), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_vehicles_plat_nomor'), 'customer_vehicles', ['plat_nomor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_vehicles_plat_nomor'), table_name='customer_vehicles')
    op.drop_table('customer_vehicles')
    # ### end Alembic commands ###
