"""Add bank and rekening to suppliers

Revision ID: ebc57ae18532
Revises: dc089e57af55
Create Date: 2026-01-31 11:17:26.708516+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc57ae18532'
down_revision: Union[str, None] = 'dc089e57af55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('bank', sa.String(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('rekening', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'rekening')
    op.drop_column('suppliers', 'bank')
    # ### end Alembic commands ###
