"""add_linking_fields_to_pengeluaran_bengkel

Revision ID: d74a1e33b767
Revises: 008fcf7131f1
Create Date: 2026-03-16 21:30:30.408646+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74a1e33b767'
down_revision: Union[str, None] = '008fcf7131f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
