"""add workshop status

Revision ID: dc089e57af55
Revises: eecc5c18e8c0
Create Date: 2026-01-31 09:28:24.434508+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc089e57af55'
down_revision: Union[str, None] = 'eecc5c18e8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaksi_penjualan_bengkel', sa.Column('status_pengerjaan', sa.Enum('ANTRE', 'PROSES', 'SELESAI', 'BATAL', name='workshopstatus'), nullable=False))
    op.create_index(op.f('ix_transaksi_penjualan_bengkel_status_pengerjaan'), 'transaksi_penjualan_bengkel', ['status_pengerjaan'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaksi_penjualan_bengkel_status_pengerjaan'), table_name='transaksi_penjualan_bengkel')
    op.drop_column('transaksi_penjualan_bengkel', 'status_pengerjaan')
    # ### end Alembic commands ###
