"""add phone to users

Revision ID: df64ee66aab1
Revises: 20260212_171700
Create Date: 2026-02-20 22:00:52.895339+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df64ee66aab1'
down_revision: Union[str, None] = '20260212_171700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('absensi', 'status',
               existing_type=mysql.ENUM('HADIR', 'IZIN', 'SAKIT', 'ALPHA', 'CUTI', 'SETENGAH_HARI', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'HADIR'"))
    op.alter_column('armada_jasa_angkut', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('armada_jasa_angkut', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('armada_jasa_angkut', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('nopol', table_name='armada_jasa_angkut')
    op.drop_index('nopol_2', table_name='armada_jasa_angkut')
    op.create_index(op.f('ix_armada_jasa_angkut_nama'), 'armada_jasa_angkut', ['nama'], unique=False)
    op.create_index(op.f('ix_armada_jasa_angkut_nopol'), 'armada_jasa_angkut', ['nopol'], unique=True)
    op.alter_column('kas_bank', 'jenis',
               existing_type=mysql.ENUM('CASH', 'BANK_BCA', 'BANK_MANDIRI', 'BANK_BRI', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('kas_bank', 'tipe',
               existing_type=mysql.ENUM('MASUK', 'KELUAR', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('kas_bank', 'sumber',
               existing_type=mysql.ENUM('BENGKEL', 'JUAL_BELI_MOBIL', 'JASA_ANGKUT', 'PEMBELIAN_PART', 'PEMBELIAN_MOBIL', 'PENGELUARAN', 'GAJI', 'KASBON', 'PIUTANG', 'HUTANG', 'MODAL', 'PRIVE', 'LAINNYA', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('mobil', 'status_bayar_beli',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'),
               nullable=False,
               existing_server_default=sa.text("'LUNAS'"))
    op.alter_column('mobil', 'metode_bayar_beli',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', 'SPLIT', 'INTERNAL', 'OTHER', name='paymentmethod'),
               nullable=False,
               existing_server_default=sa.text("'TUNAI'"))
    op.alter_column('mobil', 'dp_beli',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('muatan_jasa_angkut', 'jenis_muatan',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('muatan_jasa_angkut', 'status_bayar',
               existing_type=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('pembayaran_piutang', 'metode_bayar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', 'SPLIT', 'INTERNAL', 'OTHER', name='paymentmethod'),
               nullable=False)
    op.alter_column('pembelian_spare_parts', 'status_bayar',
               existing_type=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'SEBAGIAN', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'),
               nullable=False)
    op.alter_column('pengeluaran_bengkel', 'metode_bayar',
               existing_type=mysql.ENUM('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', 'SPLIT', 'OTHER', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'TUNAI'"))
    op.alter_column('slip_gaji', 'jumlah_hadir',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=5, scale=1),
               existing_nullable=False)
    op.alter_column('transaksi_penjualan_bengkel', 'kategori',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=False)
    op.alter_column('transaksi_penjualan_bengkel', 'status_pengerjaan',
               existing_type=mysql.ENUM('ANTRE', 'DIPROSES', 'SELESAI', 'DIBATALKAN', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('ANTRE', 'PROSES', 'SELESAI', 'BATAL', name='workshopstatus'),
               nullable=False,
               existing_server_default=sa.text("'ANTRE'"))
    op.alter_column('transaksi_penjualan_bengkel', 'status_bayar',
               existing_type=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'SEBAGIAN', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'),
               nullable=False,
               existing_server_default=sa.text("'LUNAS'"))
    op.alter_column('transaksi_penjualan_bengkel', 'metode_bayar',
               existing_type=mysql.ENUM('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', 'SPLIT', 'OTHER', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_server_default=sa.text("'TUNAI'"))
    op.alter_column('transaksi_penjualan_mobil', 'metode_bayar',
               existing_type=mysql.ENUM('tunai', 'transfer', 'kredit', 'debit', 'split', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.alter_column('transaksi_penjualan_mobil', 'metode_bayar',
               existing_type=mysql.ENUM('tunai', 'transfer', 'kredit', 'debit', 'split', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('transaksi_penjualan_bengkel', 'metode_bayar',
               existing_type=mysql.ENUM('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', 'SPLIT', 'OTHER', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'TUNAI'"))
    op.alter_column('transaksi_penjualan_bengkel', 'status_bayar',
               existing_type=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'),
               type_=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'SEBAGIAN', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'LUNAS'"))
    op.alter_column('transaksi_penjualan_bengkel', 'status_pengerjaan',
               existing_type=sa.Enum('ANTRE', 'PROSES', 'SELESAI', 'BATAL', name='workshopstatus'),
               type_=mysql.ENUM('ANTRE', 'DIPROSES', 'SELESAI', 'DIBATALKAN', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'ANTRE'"))
    op.alter_column('transaksi_penjualan_bengkel', 'kategori',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=True)
    op.alter_column('slip_gaji', 'jumlah_hadir',
               existing_type=sa.Numeric(precision=5, scale=1),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('pengeluaran_bengkel', 'metode_bayar',
               existing_type=mysql.ENUM('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', 'SPLIT', 'OTHER', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'TUNAI'"))
    op.alter_column('pembelian_spare_parts', 'status_bayar',
               existing_type=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'),
               type_=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'SEBAGIAN', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('pembayaran_piutang', 'metode_bayar',
               existing_type=sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', 'SPLIT', 'INTERNAL', 'OTHER', name='paymentmethod'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('muatan_jasa_angkut', 'status_bayar',
               existing_type=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('muatan_jasa_angkut', 'jenis_muatan',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)
    op.alter_column('mobil', 'dp_beli',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
    op.alter_column('mobil', 'metode_bayar_beli',
               existing_type=sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', 'SPLIT', 'INTERNAL', 'OTHER', name='paymentmethod'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               existing_server_default=sa.text("'TUNAI'"))
    op.alter_column('mobil', 'status_bayar_beli',
               existing_type=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               existing_server_default=sa.text("'LUNAS'"))
    op.alter_column('kas_bank', 'sumber',
               existing_type=mysql.ENUM('BENGKEL', 'JUAL_BELI_MOBIL', 'JASA_ANGKUT', 'PEMBELIAN_PART', 'PEMBELIAN_MOBIL', 'PENGELUARAN', 'GAJI', 'KASBON', 'PIUTANG', 'HUTANG', 'MODAL', 'PRIVE', 'LAINNYA', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('kas_bank', 'tipe',
               existing_type=mysql.ENUM('MASUK', 'KELUAR', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('kas_bank', 'jenis',
               existing_type=mysql.ENUM('CASH', 'BANK_BCA', 'BANK_MANDIRI', 'BANK_BRI', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_index(op.f('ix_armada_jasa_angkut_nopol'), table_name='armada_jasa_angkut')
    op.drop_index(op.f('ix_armada_jasa_angkut_nama'), table_name='armada_jasa_angkut')
    op.create_index('nopol_2', 'armada_jasa_angkut', ['nopol'], unique=False)
    op.create_index('nopol', 'armada_jasa_angkut', ['nopol'], unique=False)
    op.alter_column('armada_jasa_angkut', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('armada_jasa_angkut', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('armada_jasa_angkut', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('absensi', 'status',
               existing_type=mysql.ENUM('HADIR', 'IZIN', 'SAKIT', 'ALPHA', 'CUTI', 'SETENGAH_HARI', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_server_default=sa.text("'HADIR'"))
    # ### end Alembic commands ###
