"""add muatan status to jasa angkut

Revision ID: 12c0273dbfc3
Revises: 9cb446e5c81c
Create Date: 2026-03-27 20:43:50.879281+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12c0273dbfc3'
down_revision: Union[str, None] = '9cb446e5c81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('muatan_jasa_angkut', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.Enum('PROSES', 'SELESAI', name='muatanstatus'),
               nullable=False,
               existing_server_default=sa.text("'PROSES'"))
    op.drop_index('idx_muatan_status', table_name='muatan_jasa_angkut')
    op.create_index(op.f('ix_muatan_jasa_angkut_status'), 'muatan_jasa_angkut', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_muatan_jasa_angkut_status'), table_name='muatan_jasa_angkut')
    op.create_index('idx_muatan_status', 'muatan_jasa_angkut', ['status'], unique=False)
    op.alter_column('muatan_jasa_angkut', 'status',
               existing_type=sa.Enum('PROSES', 'SELESAI', name='muatanstatus'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               existing_server_default=sa.text("'PROSES'"))
    # ### end Alembic commands ###
