"""update_kasbankjenis_enums

Revision ID: 89ed3ce6c6d8
Revises: 697ef77fdde1
Create Date: 2026-03-28 17:26:55.568641+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89ed3ce6c6d8'
down_revision: Union[str, None] = '697ef77fdde1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
