"""Add metode_bayar to KasBank

Revision ID: c1063bd17519
Revises: 882c79925d46
Create Date: 2026-02-01 11:35:59.557269+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1063bd17519'
down_revision: Union[str, None] = '882c79925d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kas_bank', sa.Column('metode_bayar', sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', name='paymentmethod'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kas_bank', 'metode_bayar')
    # ### end Alembic commands ###
