"""Add supir_nama nopol ritase hargabeli hargajual

Revision ID: 882c79925d46
Revises: 0e24968b2a20
Create Date: 2026-01-31 23:10:43.077898+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '882c79925d46'
down_revision: Union[str, None] = '0e24968b2a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muatan_jasa_angkut', sa.Column('supir_nama', sa.String(length=100), nullable=True))
    op.add_column('muatan_jasa_angkut', sa.Column('nopol', sa.String(length=20), nullable=True))
    op.add_column('muatan_jasa_angkut', sa.Column('ritase', sa.Integer(), nullable=False))
    op.add_column('muatan_jasa_angkut', sa.Column('harga_beli', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('muatan_jasa_angkut', sa.Column('harga_jual', sa.Numeric(precision=15, scale=2), nullable=False))
    op.alter_column('muatan_jasa_angkut', 'supir_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('muatan_jasa_angkut', 'supir_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('muatan_jasa_angkut', 'harga_jual')
    op.drop_column('muatan_jasa_angkut', 'harga_beli')
    op.drop_column('muatan_jasa_angkut', 'ritase')
    op.drop_column('muatan_jasa_angkut', 'nopol')
    op.drop_column('muatan_jasa_angkut', 'supir_nama')
    # ### end Alembic commands ###
