"""add_investor_disbursement_fields

Revision ID: 55885c6d74b4
Revises: 20260313_001000
Create Date: 2026-03-13 00:15:53.208844+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55885c6d74b4'
down_revision: Union[str, None] = '20260313_001000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jasa_angkut_biaya_lainnya_tanggal'), 'jasa_angkut_biaya_lainnya', ['tanggal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jasa_angkut_biaya_lainnya_tanggal'), table_name='jasa_angkut_biaya_lainnya')
    # ### end Alembic commands ###
