"""add user_id to kas_bank

Revision ID: e797b02fa528
Revises: d74a1e33b767
Create Date: 2026-03-17 23:18:24.954117+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e797b02fa528'
down_revision: Union[str, None] = 'd74a1e33b767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kas_bank', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_kas_bank_user_id'), 'kas_bank', ['user_id'], unique=False)
    op.create_foreign_key(None, 'kas_bank', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('ADMIN', 'MANAGER', 'KASIR', 'MEKANIK', 'STAFF', 'VIEWER', collation='utf8mb4_unicode_ci'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('ADMIN', 'MANAGER', 'KASIR', 'MEKANIK', 'STAFF', 'VIEWER', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_constraint(None, 'kas_bank', type_='foreignkey')
    op.drop_index(op.f('ix_kas_bank_user_id'), table_name='kas_bank')
    op.drop_column('kas_bank', 'user_id')
    # ### end Alembic commands ###
