"""initial_schema

Revision ID: eecc5c18e8c0
Revises: 
Create Date: 2026-01-30 21:07:13.828223+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecc5c18e8c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('tipe', sa.String(length=20), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('kota', sa.String(length=50), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('npwp', sa.String(length=30), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_kode'), 'customers', ['kode'], unique=True)
    op.create_index(op.f('ix_customers_nama'), 'customers', ['nama'], unique=False)
    op.create_table('karyawan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('jabatan', sa.String(length=50), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('tanggal_bergabung', sa.Date(), nullable=False),
    sa.Column('tanggal_keluar', sa.Date(), nullable=True),
    sa.Column('gaji_pokok', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tunjangan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AKTIF', 'TIDAK_AKTIF', 'RESIGN', name='employeestatus'), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_karyawan_kode'), 'karyawan', ['kode'], unique=True)
    op.create_index(op.f('ix_karyawan_nama'), 'karyawan', ['nama'], unique=False)
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('merek', sa.String(length=50), nullable=True),
    sa.Column('satuan', sa.String(length=20), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('stok_minimum', sa.Integer(), nullable=False),
    sa.Column('harga_beli', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('harga_jual', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('lokasi_rak', sa.String(length=30), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_parts_kode'), 'spare_parts', ['kode'], unique=True)
    op.create_index(op.f('ix_spare_parts_nama'), 'spare_parts', ['nama'], unique=False)
    op.create_table('supir',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('nomor_sim', sa.String(length=30), nullable=True),
    sa.Column('jenis_sim', sa.String(length=5), nullable=True),
    sa.Column('tanggal_bergabung', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supir_kode'), 'supir', ['kode'], unique=True)
    op.create_index(op.f('ix_supir_nama'), 'supir', ['nama'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('kota', sa.String(length=50), nullable=True),
    sa.Column('telepon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('npwp', sa.String(length=30), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_kode'), 'suppliers', ['kode'], unique=True)
    op.create_index(op.f('ix_suppliers_nama'), 'suppliers', ['nama'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'STAFF', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('absensi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('HADIR', 'IZIN', 'SAKIT', 'ALPHA', 'CUTI', name='attendancestatus'), nullable=False),
    sa.Column('jam_masuk', sa.Time(), nullable=True),
    sa.Column('jam_keluar', sa.Time(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('karyawan_id', 'tanggal', name='uq_absensi_karyawan_tanggal')
    )
    op.create_index(op.f('ix_absensi_karyawan_id'), 'absensi', ['karyawan_id'], unique=False)
    op.create_index(op.f('ix_absensi_tanggal'), 'absensi', ['tanggal'], unique=False)
    op.create_table('kas_bank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor_transaksi', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jenis', sa.Enum('CASH', 'BANK_BCA', 'BANK_MANDIRI', 'BANK_BRI', 'BANK_LAINNYA', name='kasbankjenis'), nullable=False),
    sa.Column('tipe', sa.Enum('MASUK', 'KELUAR', name='kasbanktype'), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sumber', sa.Enum('BENGKEL', 'JUAL_BELI_MOBIL', 'JASA_ANGKUT', 'PEMBELIAN_PART', 'PEMBELIAN_MOBIL', 'PENGELUARAN', 'GAJI', 'KASBON', 'PIUTANG', 'MODAL', 'PRIVE', 'LAINNYA', name='kasbanksource'), nullable=False),
    sa.Column('referensi_id', sa.Integer(), nullable=True),
    sa.Column('nomor_referensi', sa.String(length=30), nullable=True),
    sa.Column('saldo_sebelum', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_sesudah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kas_bank_jenis'), 'kas_bank', ['jenis'], unique=False)
    op.create_index(op.f('ix_kas_bank_nomor_transaksi'), 'kas_bank', ['nomor_transaksi'], unique=True)
    op.create_index(op.f('ix_kas_bank_tanggal'), 'kas_bank', ['tanggal'], unique=False)
    op.create_index(op.f('ix_kas_bank_tipe'), 'kas_bank', ['tipe'], unique=False)
    op.create_table('kasbon_karyawan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor_kasbon', sa.String(length=30), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'), nullable=False),
    sa.Column('tanggal_lunas', sa.Date(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kasbon_karyawan_karyawan_id'), 'kasbon_karyawan', ['karyawan_id'], unique=False)
    op.create_index(op.f('ix_kasbon_karyawan_nomor_kasbon'), 'kasbon_karyawan', ['nomor_kasbon'], unique=True)
    op.create_index(op.f('ix_kasbon_karyawan_tanggal'), 'kasbon_karyawan', ['tanggal'], unique=False)
    op.create_table('mobil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('merek', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('warna', sa.String(length=30), nullable=False),
    sa.Column('nomor_plat', sa.String(length=15), nullable=False),
    sa.Column('nomor_rangka', sa.String(length=50), nullable=True),
    sa.Column('nomor_mesin', sa.String(length=50), nullable=True),
    sa.Column('transmisi', sa.String(length=20), nullable=True),
    sa.Column('bahan_bakar', sa.String(length=20), nullable=True),
    sa.Column('kilometer', sa.Integer(), nullable=True),
    sa.Column('harga_beli', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('harga_jual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tipe_kepemilikan', sa.Enum('TPM', 'INVESTOR', name='ownershiptype'), nullable=False),
    sa.Column('nama_investor', sa.String(length=100), nullable=True),
    sa.Column('persentase_investor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('TERSEDIA', 'TERJUAL', 'DALAM_PERBAIKAN', 'BOOKING', name='carstatus'), nullable=False),
    sa.Column('tanggal_masuk', sa.Date(), nullable=False),
    sa.Column('tanggal_terjual', sa.Date(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobil_kode'), 'mobil', ['kode'], unique=True)
    op.create_index(op.f('ix_mobil_merek'), 'mobil', ['merek'], unique=False)
    op.create_index(op.f('ix_mobil_nomor_plat'), 'mobil', ['nomor_plat'], unique=False)
    op.create_table('muatan_jasa_angkut',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor_transaksi', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('supir_id', sa.Integer(), nullable=False),
    sa.Column('asal', sa.String(length=100), nullable=False),
    sa.Column('tujuan', sa.String(length=100), nullable=False),
    sa.Column('jenis_muatan', sa.String(length=100), nullable=True),
    sa.Column('berat_muatan', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pendapatan_kotor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('biaya_bbm', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('biaya_tol', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('biaya_makan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('biaya_parkir', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('biaya_lainnya', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_biaya', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('laba_kotor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('persentase_tpm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('laba_tpm', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('laba_supir', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status_bayar', sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'), nullable=False),
    sa.Column('tanggal_bayar', sa.Date(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supir_id'], ['supir.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muatan_jasa_angkut_nomor_transaksi'), 'muatan_jasa_angkut', ['nomor_transaksi'], unique=True)
    op.create_index(op.f('ix_muatan_jasa_angkut_tanggal'), 'muatan_jasa_angkut', ['tanggal'], unique=False)
    op.create_table('pembelian_spare_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor_transaksi', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('nomor_faktur', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('diskon', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status_bayar', sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'), nullable=False),
    sa.Column('metode_bayar', sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', name='paymentmethod'), nullable=True),
    sa.Column('tanggal_bayar', sa.Date(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pembelian_spare_parts_nomor_transaksi'), 'pembelian_spare_parts', ['nomor_transaksi'], unique=True)
    op.create_index(op.f('ix_pembelian_spare_parts_tanggal'), 'pembelian_spare_parts', ['tanggal'], unique=False)
    op.create_table('pengeluaran_bengkel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor_transaksi', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('kategori', sa.Enum('OPERASIONAL', 'PEMELIHARAAN', 'GAJI', 'UTILITAS', 'LAINNYA', name='expensecategory'), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=False),
    sa.Column('jumlah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('metode_bayar', sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', name='paymentmethod'), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pengeluaran_bengkel_nomor_transaksi'), 'pengeluaran_bengkel', ['nomor_transaksi'], unique=True)
    op.create_index(op.f('ix_pengeluaran_bengkel_tanggal'), 'pengeluaran_bengkel', ['tanggal'], unique=False)
    op.create_table('piutang_usaha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor_piutang', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('sumber', sa.Enum('BENGKEL', 'JUAL_BELI_MOBIL', 'JASA_ANGKUT', 'KASBON_KARYAWAN', 'LAINNYA', name='piutangsource'), nullable=False),
    sa.Column('referensi_id', sa.Integer(), nullable=True),
    sa.Column('nomor_referensi', sa.String(length=30), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('nama_debitur', sa.String(length=100), nullable=False),
    sa.Column('telepon_debitur', sa.String(length=20), nullable=True),
    sa.Column('alamat_debitur', sa.Text(), nullable=True),
    sa.Column('nominal_piutang', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_dibayar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sisa_piutang', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tanggal_jatuh_tempo', sa.Date(), nullable=True),
    sa.Column('tanggal_lunas', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('BELUM_LUNAS', 'LUNAS', 'SEBAGIAN', name='piutangstatus'), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_piutang_usaha_customer_id'), 'piutang_usaha', ['customer_id'], unique=False)
    op.create_index(op.f('ix_piutang_usaha_nomor_piutang'), 'piutang_usaha', ['nomor_piutang'], unique=True)
    op.create_index(op.f('ix_piutang_usaha_tanggal'), 'piutang_usaha', ['tanggal'], unique=False)
    op.create_table('slip_gaji',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor_slip', sa.String(length=30), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('periode_bulan', sa.Integer(), nullable=False),
    sa.Column('periode_tahun', sa.Integer(), nullable=False),
    sa.Column('jumlah_hari_kerja', sa.Integer(), nullable=False),
    sa.Column('jumlah_hadir', sa.Integer(), nullable=False),
    sa.Column('jumlah_izin', sa.Integer(), nullable=False),
    sa.Column('jumlah_sakit', sa.Integer(), nullable=False),
    sa.Column('jumlah_alpha', sa.Integer(), nullable=False),
    sa.Column('gaji_pokok', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tunjangan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('lembur', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('potongan_kasbon', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('potongan_lainnya', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_pendapatan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_potongan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gaji_bersih', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_dibayarkan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'), nullable=False),
    sa.Column('metode_bayar', sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', name='paymentmethod'), nullable=True),
    sa.Column('tanggal_bayar', sa.Date(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('karyawan_id', 'periode_bulan', 'periode_tahun', name='uq_slip_gaji_karyawan_periode')
    )
    op.create_index(op.f('ix_slip_gaji_karyawan_id'), 'slip_gaji', ['karyawan_id'], unique=False)
    op.create_index(op.f('ix_slip_gaji_nomor_slip'), 'slip_gaji', ['nomor_slip'], unique=True)
    op.create_table('transaksi_penjualan_bengkel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor_transaksi', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('nama_customer', sa.String(length=100), nullable=True),
    sa.Column('nomor_plat', sa.String(length=15), nullable=True),
    sa.Column('jenis_kendaraan', sa.String(length=50), nullable=True),
    sa.Column('total_parts', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_jasa', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('diskon', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('hpp_parts', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('laba_kotor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status_bayar', sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'), nullable=False),
    sa.Column('metode_bayar', sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', name='paymentmethod'), nullable=False),
    sa.Column('jumlah_bayar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('kembalian', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_penjualan_bengkel_nomor_transaksi'), 'transaksi_penjualan_bengkel', ['nomor_transaksi'], unique=True)
    op.create_index(op.f('ix_transaksi_penjualan_bengkel_tanggal'), 'transaksi_penjualan_bengkel', ['tanggal'], unique=False)
    op.create_table('detail_pembelian_spare_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pembelian_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pembelian_id'], ['pembelian_spare_parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_transaksi_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaksi_id', sa.Integer(), nullable=False),
    sa.Column('nama_jasa', sa.String(length=150), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('harga', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['transaksi_id'], ['transaksi_penjualan_bengkel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_transaksi_spare_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaksi_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_beli', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('harga_jual', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.ForeignKeyConstraint(['transaksi_id'], ['transaksi_penjualan_bengkel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jasa_angkut_biaya_lainnya',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('muatan_id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=False),
    sa.Column('jumlah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['muatan_id'], ['muatan_jasa_angkut.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jasa_angkut_part_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('muatan_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('tipe', sa.String(length=20), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['muatan_id'], ['muatan_jasa_angkut.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobil_biaya_lainnya',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobil_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=False),
    sa.Column('jumlah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mobil_id'], ['mobil.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobil_part_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobil_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('tipe', sa.String(length=20), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('harga_satuan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mobil_id'], ['mobil.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobil_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobil_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mobil_id'], ['mobil.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pembayaran_piutang',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('piutang_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('metode_bayar', sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', name='paymentmethod'), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['piutang_id'], ['piutang_usaha.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pembayaran_piutang_piutang_id'), 'pembayaran_piutang', ['piutang_id'], unique=False)
    op.create_index(op.f('ix_pembayaran_piutang_tanggal'), 'pembayaran_piutang', ['tanggal'], unique=False)
    op.create_table('transaksi_penjualan_mobil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nomor_transaksi', sa.String(length=30), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('mobil_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('nama_pembeli', sa.String(length=100), nullable=False),
    sa.Column('telepon_pembeli', sa.String(length=20), nullable=True),
    sa.Column('alamat_pembeli', sa.Text(), nullable=True),
    sa.Column('harga_jual', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_modal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('laba_kotor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tipe_kepemilikan', sa.Enum('TPM', 'INVESTOR', name='ownershiptype'), nullable=False),
    sa.Column('persentase_investor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('laba_investor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('laba_tpm', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status_bayar', sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', name='paymentstatus'), nullable=False),
    sa.Column('metode_bayar', sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', name='paymentmethod'), nullable=False),
    sa.Column('dp', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('sisa_bayar', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['mobil_id'], ['mobil.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobil_id')
    )
    op.create_index(op.f('ix_transaksi_penjualan_mobil_nomor_transaksi'), 'transaksi_penjualan_mobil', ['nomor_transaksi'], unique=True)
    op.create_index(op.f('ix_transaksi_penjualan_mobil_tanggal'), 'transaksi_penjualan_mobil', ['tanggal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaksi_penjualan_mobil_tanggal'), table_name='transaksi_penjualan_mobil')
    op.drop_index(op.f('ix_transaksi_penjualan_mobil_nomor_transaksi'), table_name='transaksi_penjualan_mobil')
    op.drop_table('transaksi_penjualan_mobil')
    op.drop_index(op.f('ix_pembayaran_piutang_tanggal'), table_name='pembayaran_piutang')
    op.drop_index(op.f('ix_pembayaran_piutang_piutang_id'), table_name='pembayaran_piutang')
    op.drop_table('pembayaran_piutang')
    op.drop_table('mobil_photos')
    op.drop_table('mobil_part_service')
    op.drop_table('mobil_biaya_lainnya')
    op.drop_table('jasa_angkut_part_service')
    op.drop_table('jasa_angkut_biaya_lainnya')
    op.drop_table('detail_transaksi_spare_parts')
    op.drop_table('detail_transaksi_services')
    op.drop_table('detail_pembelian_spare_parts')
    op.drop_index(op.f('ix_transaksi_penjualan_bengkel_tanggal'), table_name='transaksi_penjualan_bengkel')
    op.drop_index(op.f('ix_transaksi_penjualan_bengkel_nomor_transaksi'), table_name='transaksi_penjualan_bengkel')
    op.drop_table('transaksi_penjualan_bengkel')
    op.drop_index(op.f('ix_slip_gaji_nomor_slip'), table_name='slip_gaji')
    op.drop_index(op.f('ix_slip_gaji_karyawan_id'), table_name='slip_gaji')
    op.drop_table('slip_gaji')
    op.drop_index(op.f('ix_piutang_usaha_tanggal'), table_name='piutang_usaha')
    op.drop_index(op.f('ix_piutang_usaha_nomor_piutang'), table_name='piutang_usaha')
    op.drop_index(op.f('ix_piutang_usaha_customer_id'), table_name='piutang_usaha')
    op.drop_table('piutang_usaha')
    op.drop_index(op.f('ix_pengeluaran_bengkel_tanggal'), table_name='pengeluaran_bengkel')
    op.drop_index(op.f('ix_pengeluaran_bengkel_nomor_transaksi'), table_name='pengeluaran_bengkel')
    op.drop_table('pengeluaran_bengkel')
    op.drop_index(op.f('ix_pembelian_spare_parts_tanggal'), table_name='pembelian_spare_parts')
    op.drop_index(op.f('ix_pembelian_spare_parts_nomor_transaksi'), table_name='pembelian_spare_parts')
    op.drop_table('pembelian_spare_parts')
    op.drop_index(op.f('ix_muatan_jasa_angkut_tanggal'), table_name='muatan_jasa_angkut')
    op.drop_index(op.f('ix_muatan_jasa_angkut_nomor_transaksi'), table_name='muatan_jasa_angkut')
    op.drop_table('muatan_jasa_angkut')
    op.drop_index(op.f('ix_mobil_nomor_plat'), table_name='mobil')
    op.drop_index(op.f('ix_mobil_merek'), table_name='mobil')
    op.drop_index(op.f('ix_mobil_kode'), table_name='mobil')
    op.drop_table('mobil')
    op.drop_index(op.f('ix_kasbon_karyawan_tanggal'), table_name='kasbon_karyawan')
    op.drop_index(op.f('ix_kasbon_karyawan_nomor_kasbon'), table_name='kasbon_karyawan')
    op.drop_index(op.f('ix_kasbon_karyawan_karyawan_id'), table_name='kasbon_karyawan')
    op.drop_table('kasbon_karyawan')
    op.drop_index(op.f('ix_kas_bank_tipe'), table_name='kas_bank')
    op.drop_index(op.f('ix_kas_bank_tanggal'), table_name='kas_bank')
    op.drop_index(op.f('ix_kas_bank_nomor_transaksi'), table_name='kas_bank')
    op.drop_index(op.f('ix_kas_bank_jenis'), table_name='kas_bank')
    op.drop_table('kas_bank')
    op.drop_index(op.f('ix_absensi_tanggal'), table_name='absensi')
    op.drop_index(op.f('ix_absensi_karyawan_id'), table_name='absensi')
    op.drop_table('absensi')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_nama'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_kode'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_supir_nama'), table_name='supir')
    op.drop_index(op.f('ix_supir_kode'), table_name='supir')
    op.drop_table('supir')
    op.drop_index(op.f('ix_spare_parts_nama'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_kode'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_index(op.f('ix_karyawan_nama'), table_name='karyawan')
    op.drop_index(op.f('ix_karyawan_kode'), table_name='karyawan')
    op.drop_table('karyawan')
    op.drop_index(op.f('ix_customers_nama'), table_name='customers')
    op.drop_index(op.f('ix_customers_kode'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
