"""change_slip_gaji_to_weekly

Revision ID: 0e24968b2a20
Revises: ebc57ae18532
Create Date: 2026-01-31 12:24:38.358884+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e24968b2a20'
down_revision: Union[str, None] = 'ebc57ae18532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slip_gaji', sa.Column('periode_minggu', sa.Integer(), nullable=False))
    op.add_column('slip_gaji', sa.Column('tanggal_mulai', sa.Date(), nullable=False))
    op.add_column('slip_gaji', sa.Column('tanggal_akhir', sa.Date(), nullable=False))
    op.drop_constraint('uq_slip_gaji_karyawan_periode', 'slip_gaji', type_='unique')
    op.create_unique_constraint('uq_slip_gaji_karyawan_periode', 'slip_gaji', ['karyawan_id', 'periode_minggu', 'periode_tahun'])
    op.drop_column('slip_gaji', 'total_potongan')
    op.drop_column('slip_gaji', 'lembur')
    op.drop_column('slip_gaji', 'potongan_lainnya')
    op.drop_column('slip_gaji', 'bonus')
    op.drop_column('slip_gaji', 'total_dibayarkan')
    op.drop_column('slip_gaji', 'periode_bulan')
    op.drop_column('slip_gaji', 'jumlah_izin')
    op.drop_column('slip_gaji', 'total_pendapatan')
    op.drop_column('slip_gaji', 'jumlah_sakit')
    op.drop_column('slip_gaji', 'tunjangan')
    op.drop_column('slip_gaji', 'jumlah_alpha')
    op.drop_column('slip_gaji', 'jumlah_hari_kerja')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slip_gaji', sa.Column('jumlah_hari_kerja', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('slip_gaji', sa.Column('jumlah_alpha', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('slip_gaji', sa.Column('tunjangan', mysql.DECIMAL(precision=15, scale=2), nullable=False))
    op.add_column('slip_gaji', sa.Column('jumlah_sakit', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('slip_gaji', sa.Column('total_pendapatan', mysql.DECIMAL(precision=15, scale=2), nullable=False))
    op.add_column('slip_gaji', sa.Column('jumlah_izin', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('slip_gaji', sa.Column('periode_bulan', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('slip_gaji', sa.Column('total_dibayarkan', mysql.DECIMAL(precision=15, scale=2), nullable=False))
    op.add_column('slip_gaji', sa.Column('bonus', mysql.DECIMAL(precision=15, scale=2), nullable=False))
    op.add_column('slip_gaji', sa.Column('potongan_lainnya', mysql.DECIMAL(precision=15, scale=2), nullable=False))
    op.add_column('slip_gaji', sa.Column('lembur', mysql.DECIMAL(precision=15, scale=2), nullable=False))
    op.add_column('slip_gaji', sa.Column('total_potongan', mysql.DECIMAL(precision=15, scale=2), nullable=False))
    op.drop_constraint('uq_slip_gaji_karyawan_periode', 'slip_gaji', type_='unique')
    op.create_unique_constraint('uq_slip_gaji_karyawan_periode', 'slip_gaji', ['karyawan_id', 'periode_bulan', 'periode_tahun'])
    op.drop_column('slip_gaji', 'tanggal_akhir')
    op.drop_column('slip_gaji', 'tanggal_mulai')
    op.drop_column('slip_gaji', 'periode_minggu')
    # ### end Alembic commands ###
