"""add_nomor_referensi_to_pengeluaran

Revision ID: c66f34535767
Revises: e8f9a0b1c2d3
Create Date: 2026-08-02 10:46:23.695925+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c66f34535767'
down_revision: Union[str, None] = 'e8f9a0b1c2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kas_bank', 'sumber',
               existing_type=mysql.ENUM('BENGKEL', 'JUAL_BELI_MOBIL', 'JASA_ANGKUT', 'PEMBELIAN_PART', 'PEMBELIAN_MOBIL', 'PENGELUARAN', 'GAJI', 'KASBON', 'PIUTANG', 'HUTANG', 'MODAL', 'PRIVE', 'LAINNYA', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('BENGKEL', 'JUAL_BELI_MOBIL', 'JASA_ANGKUT', 'PEMBELIAN_PART', 'PEMBELIAN_MOBIL', 'PENGELUARAN', 'GAJI', 'KASBON', 'PIUTANG', 'HUTANG', 'MODAL', 'PRIVE', 'ASET', 'LAINNYA', name='kasbanksource'),
               existing_nullable=False)
    op.alter_column('kasbon_karyawan', 'status',
               existing_type=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               existing_nullable=False)
    op.alter_column('mobil', 'status_bayar_beli',
               existing_type=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'LUNAS'"))
    op.alter_column('muatan_jasa_angkut', 'status_bayar',
               existing_type=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'BELUM_LUNAS'"))
    op.alter_column('pembelian_spare_parts', 'status_bayar',
               existing_type=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               existing_nullable=False)
    op.add_column('pengeluaran_bengkel', sa.Column('nomor_referensi', sa.String(length=100), nullable=True))
    op.alter_column('slip_gaji', 'status',
               existing_type=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               existing_nullable=False)
    op.alter_column('transaksi_penjualan_bengkel', 'public_receipt_token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
    op.alter_column('transaksi_penjualan_mobil', 'status_bayar',
               existing_type=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'LUNAS'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaksi_penjualan_mobil', 'status_bayar',
               existing_type=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               type_=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'LUNAS'"))
    op.alter_column('transaksi_penjualan_bengkel', 'public_receipt_token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
    op.alter_column('slip_gaji', 'status',
               existing_type=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               type_=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('pengeluaran_bengkel', 'nomor_referensi')
    op.alter_column('pembelian_spare_parts', 'status_bayar',
               existing_type=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               type_=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('muatan_jasa_angkut', 'status_bayar',
               existing_type=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               type_=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'BELUM_LUNAS'"))
    op.alter_column('mobil', 'status_bayar_beli',
               existing_type=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               type_=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'LUNAS'"))
    op.alter_column('kasbon_karyawan', 'status',
               existing_type=sa.Enum('LUNAS', 'BELUM_LUNAS', 'CICILAN', 'BATAL', 'INTERNAL', name='paymentstatus'),
               type_=mysql.ENUM('LUNAS', 'BELUM_LUNAS', 'CICILAN', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('kas_bank', 'sumber',
               existing_type=sa.Enum('BENGKEL', 'JUAL_BELI_MOBIL', 'JASA_ANGKUT', 'PEMBELIAN_PART', 'PEMBELIAN_MOBIL', 'PENGELUARAN', 'GAJI', 'KASBON', 'PIUTANG', 'HUTANG', 'MODAL', 'PRIVE', 'ASET', 'LAINNYA', name='kasbanksource'),
               type_=mysql.ENUM('BENGKEL', 'JUAL_BELI_MOBIL', 'JASA_ANGKUT', 'PEMBELIAN_PART', 'PEMBELIAN_MOBIL', 'PENGELUARAN', 'GAJI', 'KASBON', 'PIUTANG', 'HUTANG', 'MODAL', 'PRIVE', 'LAINNYA', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    # ### end Alembic commands ###
