"""add_armada_id_to_part_service

Revision ID: 008fcf7131f1
Revises: 6fdd6b964b0d
Create Date: 2026-03-16 21:20:56.313218+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '008fcf7131f1'
down_revision: Union[str, None] = '6fdd6b964b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jasa_angkut_part_service', sa.Column('armada_id', sa.Integer(), nullable=True))
    op.alter_column('jasa_angkut_part_service', 'muatan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'jasa_angkut_part_service', 'armada_jasa_angkut', ['armada_id'], ['id'], ondelete='CASCADE')
    op.add_column('pengeluaran_bengkel', sa.Column('bisnis_kategori', sa.String(length=30), server_default='umum', nullable=False))
    op.add_column('pengeluaran_bengkel', sa.Column('muatan_id', sa.Integer(), nullable=True))
    op.add_column('pengeluaran_bengkel', sa.Column('armada_id', sa.Integer(), nullable=True))
    op.add_column('pengeluaran_bengkel', sa.Column('mobil_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pengeluaran_bengkel', 'muatan_jasa_angkut', ['muatan_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pengeluaran_bengkel', 'mobil', ['mobil_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pengeluaran_bengkel', 'armada_jasa_angkut', ['armada_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pengeluaran_bengkel', type_='foreignkey')
    op.drop_constraint(None, 'pengeluaran_bengkel', type_='foreignkey')
    op.drop_constraint(None, 'pengeluaran_bengkel', type_='foreignkey')
    op.drop_column('pengeluaran_bengkel', 'mobil_id')
    op.drop_column('pengeluaran_bengkel', 'armada_id')
    op.drop_column('pengeluaran_bengkel', 'muatan_id')
    op.drop_column('pengeluaran_bengkel', 'bisnis_kategori')
    op.drop_constraint(None, 'jasa_angkut_part_service', type_='foreignkey')
    op.alter_column('jasa_angkut_part_service', 'muatan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('jasa_angkut_part_service', 'armada_id')
    # ### end Alembic commands ###
