"""add investor disbursement detail table

Revision ID: 6fdd6b964b0d
Revises: 20260313_001000
Create Date: 2026-03-14 22:30:56.107912+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdd6b964b0d'
down_revision: Union[str, None] = '20260313_001000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Update the enum type to include SEBAGIAN
    op.execute("ALTER TABLE transaksi_penjualan_mobil MODIFY COLUMN status_pencairan ENUM('BELUM_DICAIRKAN', 'SEBAGIAN', 'DICAIRKAN') DEFAULT 'BELUM_DICAIRKAN'")

    op.create_table('investor_disbursement_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaksi_id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('nominal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('metode_bayar', sa.Enum('TUNAI', 'TRANSFER', 'KREDIT', 'DEBIT', 'SPLIT', 'INTERNAL', 'POTONG_GAJI', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaksi_id'], ['transaksi_penjualan_mobil.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investor_disbursement_detail')
    # ### end Alembic commands ###
