"""add_uang_lembur_to_slip_gaji

Revision ID: 8333db11e1b8
Revises: e2f3g4h5i6j7
Create Date: 2026-04-06 14:57:57.909316+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8333db11e1b8'
down_revision: Union[str, None] = 'e2f3g4h5i6j7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slip_gaji', sa.Column('uang_lembur', sa.Numeric(precision=15, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slip_gaji', 'uang_lembur')
    # ### end Alembic commands ###
