"""remove user_id from kas_bank

Revision ID: c4f89c096534
Revises: f4b8c9d0e1f2
Create Date: 2026-03-18 15:23:54.578012+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4f89c096534'
down_revision: Union[str, None] = 'f4b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kas_bank_user_id', table_name='kas_bank')
    op.drop_constraint('kas_bank_ibfk_2', 'kas_bank', type_='foreignkey')
    op.drop_column('kas_bank', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kas_bank', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('kas_bank_ibfk_2', 'kas_bank', 'users', ['user_id'], ['id'])
    op.create_index('ix_kas_bank_user_id', 'kas_bank', ['user_id'], unique=False)
    # ### end Alembic commands ###
