"""add_asset_table

Revision ID: f82d3e4c5b6a
Revises: b2c3d4e5f6a7
Create Date: 2026-03-04 23:55:00.000000+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82d3e4c5b6a'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aset',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('kode', sa.String(length=20), nullable=False),
        sa.Column('nama', sa.String(length=100), nullable=False),
        sa.Column('kategori', sa.Enum('KENDARAAN', 'PERALATAN', 'ELECTRONIC', 'BANGUNAN', 'TANAH', 'LAINNYA', name='assetcategory'), nullable=False),
        sa.Column('tanggal_beli', sa.Date(), nullable=False),
        sa.Column('harga_beli', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('nilai_residu', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('umur_ekonomis', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('AKTIF', 'DIJUAL', 'RUSAK', 'HILANG', name='assetstatus'), nullable=False),
        sa.Column('lokasi', sa.String(length=100), nullable=True),
        sa.Column('catatan', sa.Text(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aset_kode'), 'aset', ['kode'], unique=True)
    op.create_index(op.f('ix_aset_nama'), 'aset', ['nama'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aset_nama'), table_name='aset')
    op.drop_index(op.f('ix_aset_kode'), table_name='aset')
    op.drop_table('aset')
    # ### end Alembic commands ###
