"""add muatan status to jasa angkut

Revision ID: 12c0273dbfc3
Revises: 9cb446e5c81c
Create Date: 2026-03-27 20:43:50.879281+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '12c0273dbfc3'
down_revision: Union[str, None] = '9cb446e5c81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Dapatkan koneksi dan inspektor database
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    column_names = [c['name'] for c in inspector.get_columns('muatan_jasa_angkut')]
    
    # Jika kolom status belum ada (seperti di VPS), tambahkan kolomnya
    if 'status' not in column_names:
        op.add_column('muatan_jasa_angkut', 
            sa.Column('status', sa.Enum('PROSES', 'SELESAI', name='muatanstatus'), nullable=False, server_default='PROSES')
        )
    else:
        # Jika kolom status sudah ada (seperti di Lokal), ubah tipenya ke Enum
        op.alter_column('muatan_jasa_angkut', 'status',
                   existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
                   type_=sa.Enum('PROSES', 'SELESAI', name='muatanstatus'),
                   nullable=False,
                   existing_server_default=sa.text("'PROSES'"))
    
    # Hapus index manual lama jika ada (idx_muatan_status)
    indices = [i['name'] for i in inspector.get_indexes('muatan_jasa_angkut')]
    if 'idx_muatan_status' in indices:
        op.drop_index('idx_muatan_status', table_name='muatan_jasa_angkut')
    
    # Buat index baru yang terstandarisasi Alembic jika belum ada
    if op.f('ix_muatan_jasa_angkut_status') not in indices:
        op.create_index(op.f('ix_muatan_jasa_angkut_status'), 'muatan_jasa_angkut', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Untuk downgrade, hapus saja kolom status (ini akan menghapus index-nya juga)
    op.drop_index(op.f('ix_muatan_jasa_angkut_status'), table_name='muatan_jasa_angkut')
    op.drop_column('muatan_jasa_angkut', 'status')
    # ### end Alembic commands ###
