"""add_armada_id_to_bengkel_transaction

Revision ID: 6fee9131b52f
Revises: 7aa25f4a7e70
Create Date: 2026-02-20 22:24:59.592850+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fee9131b52f'
down_revision: Union[str, None] = '7aa25f4a7e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaksi_penjualan_bengkel', sa.Column('armada_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaksi_penjualan_bengkel', 'armada_jasa_angkut', ['armada_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaksi_penjualan_bengkel', type_='foreignkey')
    op.drop_column('transaksi_penjualan_bengkel', 'armada_id')
    # ### end Alembic commands ###
