"""Add nominal_investor to Mobil table

Revision ID: cb53d69138fe
Revises: c1063bd17519
Create Date: 2026-02-01 13:24:16.137514+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb53d69138fe'
down_revision: Union[str, None] = 'c1063bd17519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobil', sa.Column('nominal_investor', sa.Numeric(precision=15, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mobil', 'nominal_investor')
    # ### end Alembic commands ###
