#!/usr/bin/env bash
set -euo pipefail

# Generate GitHub PR body from git history + diff.
# Usage:
#   ./scripts/pr-body.sh [base] [head]
#   ./scripts/pr-body.sh main dev > /tmp/pr-body.md
#
# Examples:
#   ./scripts/pr-body.sh                    # main..current branch
#   ./scripts/pr-body.sh main dev
#   ./scripts/pr-body.sh origin/main dev

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BASE_REF="${1:-main}"
HEAD_REF="${2:-$(git -C "$PROJECT_DIR" rev-parse --abbrev-ref HEAD)}"
MAX_FILES="${MAX_FILES:-80}"

die() { echo "Error: $*" >&2; exit 1; }

resolve_ref() {
    local ref="$1"
    if git -C "$PROJECT_DIR" rev-parse --verify "$ref" &>/dev/null; then
        echo "$ref"
        return
    fi
    if git -C "$PROJECT_DIR" rev-parse --verify "origin/$ref" &>/dev/null; then
        echo "origin/$ref"
        return
    fi
    die "Ref tidak ditemukan: $ref"
}

status_label() {
    case "$1" in
        A) echo "Added" ;;
        M) echo "Modified" ;;
        D) echo "Deleted" ;;
        R*) echo "Renamed" ;;
        C*) echo "Copied" ;;
        T) echo "Type change" ;;
        *) echo "$1" ;;
    esac
}

area_label() {
    local path="$1"
    case "$path" in
        frontend/*) echo "frontend" ;;
        backend/*) echo "backend" ;;
        scripts/*) echo "scripts" ;;
        .github/*) echo "github" ;;
        .agent/*) echo "docs" ;;
        *) echo "other" ;;
    esac
}

BASE="$(resolve_ref "$BASE_REF")"
HEAD="$(resolve_ref "$HEAD_REF")"

if ! git -C "$PROJECT_DIR" merge-base --is-ancestor "$BASE" "$HEAD" 2>/dev/null; then
    die "HEAD ($HEAD) bukan descendant dari BASE ($BASE). Pastikan branch sudah di-push dan base benar."
fi

RANGE="$BASE..$HEAD"
COMMIT_COUNT="$(git -C "$PROJECT_DIR" rev-list --count "$RANGE" 2>/dev/null || echo 0)"

if [ "$COMMIT_COUNT" -eq 0 ]; then
    die "Tidak ada commit antara $BASE_REF dan $HEAD_REF."
fi

FIRST_SUBJECT="$(git -C "$PROJECT_DIR" log -1 --format=%s "$RANGE")"
BASE_NAME="${BASE_REF#origin/}"
HEAD_NAME="${HEAD_REF#origin/}"
SHORTSTAT="$(git -C "$PROJECT_DIR" diff --shortstat "$RANGE" 2>/dev/null | sed 's/^ //')"
MAX_COMMITS="${MAX_COMMITS:-20}"

# ─── Output PR body ────────────────────────────────────────────
cat <<EOF
## Summary

Merge \`$HEAD_NAME\` -> \`$BASE_NAME\` ($COMMIT_COUNT commit).

**Highlight:** $FIRST_SUBJECT

## Changes

EOF

COMMIT_LISTED=0
while IFS= read -r subject; do
    [ -z "$subject" ] && continue
    COMMIT_LISTED=$((COMMIT_LISTED + 1))
    echo "- $subject"
done < <(git -C "$PROJECT_DIR" log --format='%s' -n "$MAX_COMMITS" "$RANGE")

if [ "$COMMIT_COUNT" -gt "$MAX_COMMITS" ]; then
    REMAINING=$((COMMIT_COUNT - MAX_COMMITS))
    echo "- _...and $REMAINING more commits_"
fi

cat <<'EOF'

## Files Changed

| File | Type | Area |
|------|------|------|
EOF

FILE_COUNT=0
while IFS=$'\t' read -r status path extra; do
    [ -z "${path:-}" ] && continue
    FILE_COUNT=$((FILE_COUNT + 1))
    if [ "$FILE_COUNT" -gt "$MAX_FILES" ]; then
        echo "| _…and more_ | — | — |"
        break
    fi

    display_path="$path"
    if [[ "$status" == R* ]] && [ -n "${extra:-}" ]; then
        display_path="$path -> $extra"
    fi

    area="$(area_label "$path")"
    label="$(status_label "$status")"
    echo "| \`$display_path\` | $label | $area |"
done < <(git -C "$PROJECT_DIR" diff --name-status "$RANGE")

if [ "$FILE_COUNT" -eq 0 ]; then
    echo "| _No file changes_ | — | — |"
fi

if [ -n "$SHORTSTAT" ]; then
    echo ""
    echo "**Stats:** $SHORTSTAT"
fi

cat <<EOF

## Testing

- [ ] Needs testing — fill in after review

## Related Issues

None

---
_Auto-generated by \`scripts/pr-body.sh $BASE_REF $HEAD_REF\`_
EOF